var abi = /* abi as generated by the compiler */;
var MyContract = web3.eth.contract(abi);
var myContractInstance = MyContract.at('0x.....');

var event = myContractInstance.MyEvent({some: 'args'}, {fromBlock: 0, toBlock: 'latest'});

// watch for changes
event.watch(function(error, result){
  if (!error)
    console.log(result);
});

// Or pass a callback to start watching immediately
var event = myContractInstance.MyEvent([{some: 'args'}, {fromBlock: 0, toBlock: 'latest'}); , function(error, result){
  if (!error)
    console.log(result);
});
